#logging:
#  level:
#    org.springframework: info
#
#spring:
#  datasource:
#    hikari:
#      jdbc-url: jdbc:mysql://localhost:3306/shopping_practice
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: rene
#    password: itiswhatitis
#  jpa:
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#    hibernate:
#      ddl-auto: create
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    defer-datasource-initialization: true
#  sql:
#    init:
#      mode: always
#  devtools:
#    livereload:
#      enabled: true
#  thymeleaf:
#    cache: false
#
#spring:
#  security:
#    ignored: /resources/**,/login.html,/login-error.html
#
#spring:
#  servlet:
#    multipart:
#      max-file-size: 20MB
#      max-request-size: 100MB
#
#itemImageLocation: /Users/Rene/Documents/rene/projectFiles/jpa-shopping-practice-files/img
#
#uploadPath: /Users/Rene/Documents/rene/projectFiles/jpa-shopping-practice-files
